sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor

language:
  - php
  - node_js

php:
  - 5.3
  - 7.0
  - 7.1

env:
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

install:
  - nvm install 6 && nvm use 6
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

before_script:
  - |
    # Remove Xdebug for a huge performance increase:
    stable='^[0-9\.]+$'
    if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
      phpenv config-rm xdebug.ini
    fi

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
    # Push coverage off to Codecov
  - |
    if [[ "$WP_TRAVISCI" == "codecoverage" ]] && [ -e "/tmp/wordpress/src/wp-content/plugins/GlotPress-WP/build/logs/clover.xml" ] ; then
      bash <(curl -s https://codecov.io/bash) -f /tmp/wordpress/src/wp-content/plugins/GlotPress-WP/build/logs/clover.xml
    fi
  - |
    source $DEV_LIB_PATH/travis.after_script.sh

notifications:
  slack: hkdc:yVT7G0KeSo1iXax8lgxtjt8u
